name: dbt run on Pull Requests

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write

env:
  DBT_PROFILES_DIR: ./.github/profiles

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: astrafy-challenge-sonia-001
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dbt-bigquery
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-bigquery>=1.6,<2.0"
      - name: Create dbt profile
        run: |
          mkdir -p .github/profiles
          cat > .github/profiles/profiles.yml <<'PROF'
          bch_project:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: oauth
                project: astrafy-challenge-sonia-001
                dataset: staging
                location: US
                threads: 4
          PROF
      - name: dbt deps
        run: dbt deps --project-dir .
      - name: dbt run
        run: dbt run --project-dir . -s stg_bch_transactions_last_3m address_current_balance
      - name: dbt test
        run: dbt test --project-dir . -s stg_bch_transactions_last_3m address_current_balance
